language: ruby
rvm:
  - 2.4.1

cache: bundler

script:

  - bundle exec rake db:create db:migrate
  - bundle exec rake spec
  - bundle exec rubocop
  - bundle exec reek
  - bundle exec rails_best_practices -e "db/migrate,vendor" .
  
services:
  - mongodb

before_script:
  - cp config/mongoid.yml.example config/dmongoid.yml